In [1]:
import numpy as np

In [2]:
#numpy.where(condition, x, y)


In [3]:
arr = np.array([1, 2, 3, 4, 5])
indices = np.where(arr > 2)
indices

(array([2, 3, 4], dtype=int64),)

In [4]:
new_arr = np.where(arr > 2, arr, 0)
new_arr

array([0, 0, 3, 4, 5])

In [6]:
#zip(iterable1, iterable2, ...)


(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [7]:
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']

for item1, item2 in zip(list1, list2):
    print(item1, item2)


1 a
2 b
3 c
